import { StatusBar } from 'expo-status-bar';
import * as Notifications from 'expo-notifications';
import { ActivityIndicator, BackHandler, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ReactNode } from 'react';
import { useEffect, useState } from 'react';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { AddTransactionScreen } from './src/screens/AddTransactionScreen';
import { AuthScreen } from './src/screens/AuthScreen';
import { DashboardScreen } from './src/screens/DashboardScreen';
import { PeopleScreen } from './src/screens/PeopleScreen';
import { PersonDetailsScreen } from './src/screens/PersonDetailsScreen';
import { ReminderSettingsScreen } from './src/screens/ReminderSettingsScreen';
import { SplashScreen } from './src/screens/SplashScreen';
import { WelcomeScreen } from './src/screens/WelcomeScreen';
import { useAppRootState } from './src/screens/AppRoot';

type AppScreen='welcome'|'signin'|'signup'|'forgotPassword'|'resetPassword'|'dashboard'|'add'|'people'|'personDetails'|'reminders';
export default function App(){return <SafeAreaProvider><AppContent/></SafeAreaProvider>}
function AppContent(){const app=useAppRootState();const [personScreen,setPersonScreen]=useState<string|null>(null);const [pendingNotificationId,setPendingNotificationId]=useState<string|null>(null);const [showSplash,setShowSplash]=useState(true);useEffect(()=>{const timer=setTimeout(()=>setShowSplash(false),1800);return()=>clearTimeout(timer)},[]);useEffect(()=>{const handle=(response:Notifications.NotificationResponse)=>{const id=response.notification.request.content.data?.transactionId;if(typeof id==='string')setPendingNotificationId(id)};const sub=Notifications.addNotificationResponseReceivedListener(handle);void Notifications.getLastNotificationResponseAsync().then(r=>{if(r)handle(r)});return()=>sub.remove()},[]);useEffect(()=>{if(!pendingNotificationId||!app.transactions.length)return;const transaction=app.transactions.find(item=>item.id===pendingNotificationId);if(!transaction)return;setPersonScreen(transaction.person);app.clearMessage();app.setScreen('personDetails');setPendingNotificationId(null)},[pendingNotificationId,app.transactions]);useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{const previous:Partial<Record<AppScreen,AppScreen>>={signin:'welcome',signup:'welcome',forgotPassword:'signin',resetPassword:'signin',add:app.addReturnScreen==='personDetails'?'personDetails':'dashboard',people:'dashboard',personDetails:'people',reminders:'dashboard'};const target=previous[app.screen as AppScreen];if(!target)return false;app.clearMessage();app.setScreen(target);return true});return()=>sub.remove()},[app.screen,app.addReturnScreen]);
if(showSplash)return <AppShell><SplashScreen/></AppShell>;
if(app.loading)return <AppShell><View style={styles.loading}><ActivityIndicator size="large" color="#0F766E"/><Text style={styles.loadingText}>Loading OweMate…</Text></View></AppShell>;
if(app.screen==='welcome')return <AppShell><WelcomeScreen onSignIn={()=>{app.clearMessage();app.setScreen('signin')}} onSignUp={()=>{app.clearMessage();app.setScreen('signup')}}/></AppShell>;
if(app.screen==='signin'||app.screen==='signup')return <AppShell><AuthScreen mode={app.screen} email={app.email} password={app.password} submitting={app.authSubmitting} configured={app.configured} message={app.message?.text??null} messageType={app.message?.type??'error'} onEmailChange={app.setEmail} onPasswordChange={app.setPassword} onSubmit={()=>void app.handleAuth()} onForgotPassword={()=>{app.clearMessage();app.setScreen('forgotPassword')}} onBack={()=>{app.clearMessage();app.setScreen('welcome')}}/></AppShell>;
if(app.screen==='forgotPassword')return <AppShell><RecoveryScreen title="Forgot Password?" subtitle="Enter your account email and we'll send you a secure reset link." email={app.email} submitting={app.authSubmitting} message={app.message} button="Send Reset Link" onEmail={app.setEmail} onSubmit={()=>void app.handleForgotPassword()} onBack={()=>{app.clearMessage();app.setScreen('signin')}}/></AppShell>;
if(app.screen==='resetPassword')return <AppShell><NewPasswordScreen password={app.newPassword} submitting={app.authSubmitting} message={app.message} onPassword={app.setNewPassword} onSubmit={()=>void app.handleUpdatePassword()} onBack={()=>{app.clearMessage();app.setScreen('signin')}}/></AppShell>;
if(app.screen==='add')return <AppShell><AddTransactionScreen entryType={app.entryType} person={app.person} amount={app.amount} dueDate={app.dueDate} saving={app.saving} note={app.note} message={app.message?.text??null} reminderEnabled={app.remindersEnabled} onReminderChange={value=>void app.setReminderPreference(value)} onEntryTypeChange={app.setEntryType} onPersonChange={app.setPerson} onAmountChange={app.setAmount} onDueDateChange={app.setDueDate} onNoteChange={app.setNote} onSave={()=>void app.handleSaveTransaction()} onBack={()=>{app.clearMessage();app.setScreen(app.addReturnScreen)}}/></AppShell>;
if(app.screen==='reminders')return <AppShell><ReminderSettingsScreen enabled={app.remindersEnabled} onEnabledChange={(value)=>void app.setReminderPreference(value)} onBack={()=>app.setScreen('dashboard')}/></AppShell>;
if(app.screen==='personDetails'&&personScreen)return <AppShell><PersonDetailsScreen person={personScreen} transactions={app.transactions} onBack={()=>app.setScreen('people')} onAdd={()=>app.startAddTransaction(personScreen,'personDetails')} onToggleSettled={t=>void app.handleToggleSettled(t)}/></AppShell>;
if(app.screen==='people')return <AppShell><PeopleScreen transactions={app.transactions} onBack={()=>app.setScreen('dashboard')} onSelectPerson={person=>{setPersonScreen(person);app.setScreen('personDetails')}}/></AppShell>;
return <AppShell><DashboardScreen transactions={app.transactions} onAdd={()=>app.startAddTransaction()} onPeople={()=>app.setScreen('people')} onReminders={()=>app.setScreen('reminders')} onSignOut={()=>void app.handleSignOut()} onToggleSettled={t=>void app.handleToggleSettled(t)} onDelete={t=>void app.handleDeleteTransaction(t.id)}/></AppShell>}
function AppShell({children}:{children:ReactNode}){return <SafeAreaView style={styles.safeArea} edges={['top','bottom','left','right']}><StatusBar style="dark"/>{children}</SafeAreaView>}
function RecoveryScreen({title,subtitle,email,submitting,message,button,onEmail,onSubmit,onBack}:{title:string;subtitle:string;email:string;submitting:boolean;message:{type:'error'|'success';text:string}|null;button:string;onEmail:(v:string)=>void;onSubmit:()=>void;onBack:()=>void}){return <KeyboardAvoidingView style={styles.recoveryKeyboard} behavior={Platform.OS==='ios'?'padding':'height'}><View style={styles.recovery}><Pressable onPress={onBack}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.recoveryTitle}>{title}</Text><Text style={styles.recoverySubtitle}>{subtitle}</Text>{message&&<View style={[styles.recoveryMessage,message.type==='error'?styles.error:styles.success]}><Text style={styles.messageText}>{message.text}</Text></View>}<Text style={styles.label}>Email</Text><TextInput value={email} onChangeText={onEmail} placeholder="you@example.com" placeholderTextColor="#9AA7A5" keyboardType="email-address" autoCapitalize="none" style={styles.recoveryInput}/><Pressable style={[styles.primary,submitting&&styles.disabled]} disabled={submitting} onPress={onSubmit}>{submitting?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>{button}</Text>}</Pressable></View></KeyboardAvoidingView>}
function NewPasswordScreen({password,submitting,message,onPassword,onSubmit,onBack}:{password:string;submitting:boolean;message:{type:'error'|'success';text:string}|null;onPassword:(v:string)=>void;onSubmit:()=>void;onBack:()=>void}){return <KeyboardAvoidingView style={styles.recoveryKeyboard} behavior={Platform.OS==='ios'?'padding':'height'}><View style={styles.recovery}><Pressable onPress={onBack}><Text style={styles.back}>‹  Back</Text></Pressable><Text style={styles.recoveryTitle}>Set New Password</Text><Text style={styles.recoverySubtitle}>Choose a new password with at least 6 characters.</Text>{message&&<View style={[styles.recoveryMessage,message.type==='error'?styles.error:styles.success]}><Text style={styles.messageText}>{message.text}</Text></View>}<Text style={styles.label}>New Password</Text><TextInput value={password} onChangeText={onPassword} placeholder="New password" placeholderTextColor="#9AA7A5" secureTextEntry style={styles.recoveryInput} onSubmitEditing={onSubmit}/><Pressable style={[styles.primary,submitting&&styles.disabled]} disabled={submitting} onPress={onSubmit}>{submitting?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Update Password</Text>}</Pressable></View></KeyboardAvoidingView>}
const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:'#F4F7F6'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:12},loadingText:{color:'#64748B',fontSize:14},recoveryKeyboard:{flex:1},recovery:{flex:1,padding:20,paddingTop:10},back:{fontSize:14,fontWeight:'700',color:'#52635F',marginBottom:35},recoveryTitle:{fontSize:28,fontWeight:'900',color:'#10201D'},recoverySubtitle:{fontSize:14,lineHeight:21,color:'#6B7D79',marginTop:8,marginBottom:28},label:{fontSize:12,fontWeight:'800',color:'#40524E',marginBottom:7},recoveryInput:{height:52,borderWidth:1,borderColor:'#D6E1DE',borderRadius:14,backgroundColor:'#fff',paddingHorizontal:14,fontSize:15,color:'#12221F',marginBottom:14},primary:{height:52,borderRadius:16,backgroundColor:'#0F766E',alignItems:'center',justifyContent:'center'},disabled:{opacity:.55},primaryText:{color:'#fff',fontSize:15,fontWeight:'900'},recoveryMessage:{padding:12,borderRadius:13,marginBottom:16},error:{backgroundColor:'#FFF1F2'},success:{backgroundColor:'#ECFDF5'},messageText:{fontSize:12,lineHeight:18,color:'#334155'}});
