import { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { Transaction, TransactionStatus, TransactionType } from '../types/transaction';
import { isSupabaseConfigured, supabase } from '../lib/supabaseClient';
import { signIn, signUp } from '../services/auth';
import { createCloudTransaction, deleteCloudTransaction, fetchCloudTransactions, updateTransactionStatus } from '../services/transactions';
import { requestNotificationPermissions, scheduleDueDateReminder, syncTransactionReminders } from '../services/notifications';
import { isValidUserDate } from '../utils/date';

type Screen = 'welcome' | 'signin' | 'signup' | 'dashboard' | 'add' | 'people' | 'personDetails' | 'reminders';
type Message = { type: 'error' | 'success'; text: string } | null;
const REMINDERS_KEY = '@owemate/reminders-enabled';
function getSupabaseErrorMessage(error: unknown, fallback: string): string { if (error instanceof Error && error.message) return error.message; if (typeof error === 'object' && error !== null) { const value = error as { message?: unknown; details?: unknown; hint?: unknown; code?: unknown }; const parts = [value.message, value.details, value.hint, value.code].filter((part): part is string => typeof part === 'string' && part.length > 0); if (parts.length) return parts.join(' — '); } return fallback; }
export function useAppRootState() {
  const [screen,setScreen]=useState<Screen>('welcome'); const [addReturnScreen,setAddReturnScreen]=useState<Screen>('dashboard'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [userId,setUserId]=useState<string|null>(null); const [transactions,setTransactions]=useState<Transaction[]>([]); const [loading,setLoading]=useState(false); const [authSubmitting,setAuthSubmitting]=useState(false); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<Message>(null); const [entryType,setEntryType]=useState<TransactionType>('lent'); const [person,setPerson]=useState(''); const [amount,setAmount]=useState(''); const [dueDate,setDueDate]=useState(''); const [note,setNote]=useState(''); const [remindersEnabled,setRemindersEnabled]=useState(true); const [reminderPreferenceLoaded,setReminderPreferenceLoaded]=useState(false);
  useEffect(()=>{void AsyncStorage.getItem(REMINDERS_KEY).then(value=>{setRemindersEnabled(value !== 'false');setReminderPreferenceLoaded(true)}).catch(()=>setReminderPreferenceLoaded(true));},[]);
  useEffect(()=>{if(!supabase)return;let active=true;const client=supabase;void client.auth.getSession().then(({data})=>{if(active)setUserId(data.session?.user.id??null)});const {data}=client.auth.onAuthStateChange((_event,session)=>{if(active)setUserId(session?.user.id??null)});return()=>{active=false;data.subscription.unsubscribe()};},[]);
  useEffect(()=>{if(!userId||!reminderPreferenceLoaded){if(!userId){setTransactions([]);setLoading(false)}return}const load=async()=>{setLoading(true);setMessage(null);try{const loaded=await fetchCloudTransactions(userId);setTransactions(loaded);void syncTransactionReminders(loaded,remindersEnabled).catch(()=>undefined)}catch(error){setTransactions([]);setMessage({type:'error',text:getSupabaseErrorMessage(error,'Could not load your records.')})}finally{setLoading(false)}};void load()},[userId,reminderPreferenceLoaded]);
  const clearMessage=()=>setMessage(null);const startAddTransaction=(prefillPerson='',returnScreen:Screen='dashboard')=>{setAddReturnScreen(returnScreen);setPerson(prefillPerson);setAmount('');setDueDate('');setNote('');setEntryType('lent');clearMessage();setScreen('add')};const resetEntry=()=>{setPerson('');setAmount('');setDueDate('');setNote('');setEntryType('lent')};
  const handleAuth=async()=>{clearMessage();const cleanEmail=email.trim().toLowerCase();if(!cleanEmail||!password){setMessage({type:'error',text:'Enter your email and password.'});return}if(!isSupabaseConfigured){setMessage({type:'error',text:'Supabase is not configured in this local environment.'});return}setAuthSubmitting(true);try{const result=screen==='signin'?await signIn(cleanEmail,password):await signUp(cleanEmail,password);if(result.error)throw result.error;if(result.data.session){setScreen('dashboard');setMessage({type:'success',text:screen==='signin'?'Signed in successfully.':'Account created successfully.'})}else setMessage({type:'success',text:'Account created. Check your email if confirmation is enabled.'})}catch(error){setMessage({type:'error',text:getSupabaseErrorMessage(error,'Authentication failed.')})}finally{setAuthSubmitting(false)}};
  const handleSaveTransaction=async()=>{clearMessage();const numericAmount=Number(amount.replace(/,/g,''));const cleanDueDate=dueDate.trim();if(!userId){setMessage({type:'error',text:'Please sign in before adding a money record.'});setScreen('signin');return}if(!person.trim()||!Number.isFinite(numericAmount)||numericAmount<=0){setMessage({type:'error',text:'Enter a person and a valid amount.'});return}if(cleanDueDate&&!isValidUserDate(cleanDueDate)){setMessage({type:'error',text:'Enter a valid commitment date, for example 28 Aug 2026.'});return}const draft={person:person.trim(),amount:numericAmount,type:entryType,dueDate:cleanDueDate||'No date set',note:note.trim()||'No note'} satisfies Omit<Transaction,'id'|'createdAt'|'status'>;setSaving(true);try{const transaction=await createCloudTransaction(userId,draft);const next=[transaction,...transactions];setTransactions(next);if(remindersEnabled)void scheduleDueDateReminder(transaction).catch(()=>undefined);void syncTransactionReminders(next,remindersEnabled).catch(()=>undefined);const destination=addReturnScreen;resetEntry();setMessage({type:'success',text:'Money record saved.'});setScreen(destination);setAddReturnScreen('dashboard')}catch(error){setMessage({type:'error',text:getSupabaseErrorMessage(error,'Could not save the record.')})}finally{setSaving(false)}};
  const handleToggleSettled=async(transaction:Transaction)=>{if(!userId)return;const nextStatus:TransactionStatus=transaction.status==='settled'?'pending':'settled';try{await updateTransactionStatus(userId,transaction.id,nextStatus);const next=transactions.map(item=>item.id===transaction.id?{...item,status:nextStatus}:item);setTransactions(next);void syncTransactionReminders(next,remindersEnabled).catch(()=>undefined);setMessage({type:'success',text:nextStatus==='settled'?'Record marked as repaid.':'Record reopened.'})}catch(error){setMessage({type:'error',text:getSupabaseErrorMessage(error,'Could not update the record.')})}};
  const handleDeleteTransaction=async(transactionId:string)=>{if(!userId)return;try{await deleteCloudTransaction(userId,transactionId);const next=transactions.filter(item=>item.id!==transactionId);setTransactions(next);void syncTransactionReminders(next,remindersEnabled).catch(()=>undefined)}catch(error){setMessage({type:'error',text:getSupabaseErrorMessage(error,'Could not delete the record.')})}};
  const handleSignOut=async()=>{if(supabase)await supabase.auth.signOut();setUserId(null);setTransactions([]);setScreen('welcome');clearMessage()};const setReminderPreference=async(enabled:boolean)=>{setRemindersEnabled(enabled);await AsyncStorage.setItem(REMINDERS_KEY,String(enabled)).catch(()=>undefined);if(enabled){const granted=await requestNotificationPermissions();if(!granted){setRemindersEnabled(false);await AsyncStorage.setItem(REMINDERS_KEY,'false').catch(()=>undefined);setMessage({type:'error',text:'Notification permission was not granted.'});return}void syncTransactionReminders(transactions,true).catch(()=>undefined);setMessage({type:'success',text:'Reminders turned on.'})}else{void syncTransactionReminders(transactions,false).catch(()=>undefined);setMessage({type:'success',text:'Reminders turned off.'})}};
  return {screen,setScreen,configured:isSupabaseConfigured,email,password,userId,transactions,loading,authSubmitting,saving,message,entryType,person,amount,dueDate,note,addReturnScreen,remindersEnabled,setEmail,setPassword,setEntryType,setPerson,setAmount,setDueDate,setNote,clearMessage,handleAuth,handleSaveTransaction,handleToggleSettled,handleDeleteTransaction,handleSignOut,startAddTransaction,setReminderPreference};
}
