import { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import type { Transaction, TransactionStatus, TransactionType } from '../types/transaction';
import { isSupabaseConfigured, supabase } from '../lib/supabaseClient';
import { sendPasswordReset, signIn, signUp, updatePassword } from '../services/auth';
import { createCloudTransaction, deleteCloudTransaction, fetchCloudTransactions, updateTransactionStatus } from '../services/transactions';
import { requestNotificationPermissions, syncTransactionReminders } from '../services/notifications';
import { isValidUserDate } from '../utils/date';

type Screen='welcome'|'signin'|'signup'|'forgotPassword'|'resetPassword'|'dashboard'|'add'|'people'|'personDetails'|'reminders'|'profile'|'calendar'|'notifications'; type Message={type:'error'|'success';text:string}|null; const REMINDERS_KEY='@owemate/reminders-enabled';
function getSupabaseErrorMessage(error:unknown,fallback:string){if(error instanceof Error&&error.message)return error.message;return fallback;}
export function useAppRootState(){const [screen,setScreen]=useState<Screen>('welcome'),[addReturnScreen,setAddReturnScreen]=useState<Screen>('dashboard'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[fullName,setFullName]=useState(''),[newPassword,setNewPassword]=useState(''),[userId,setUserId]=useState<string|null>(null),[transactions,setTransactions]=useState<Transaction[]>([]),[loading,setLoading]=useState(false),[authSubmitting,setAuthSubmitting]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState<Message>(null),[entryType,setEntryType]=useState<TransactionType>('lent'),[person,setPerson]=useState(''),[amount,setAmount]=useState(''),[dueDate,setDueDate]=useState(''),[note,setNote]=useState(''),[remindersEnabled,setRemindersEnabled]=useState(true),[reminderPreferenceLoaded,setReminderPreferenceLoaded]=useState(false);const clearMessage=()=>setMessage(null);
useEffect(()=>{void AsyncStorage.getItem(REMINDERS_KEY).then(v=>setRemindersEnabled(v!=='false')).finally(()=>setReminderPreferenceLoaded(true));},[]);
useEffect(()=>{if(!supabase)return;let active=true;const applyUser=(user:any)=>{if(!active)return;setUserId(user?.id??null);setEmail(user?.email??'');setFullName(typeof user?.user_metadata?.full_name==='string'?user.user_metadata.full_name:'');};void supabase.auth.getSession().then(({data})=>applyUser(data.session?.user));const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{applyUser(session?.user);if(event==='PASSWORD_RECOVERY'){setNewPassword('');clearMessage();setScreen('resetPassword');}});return()=>{active=false;subscription.unsubscribe();};},[]);
useEffect(()=>{if(!userId||!reminderPreferenceLoaded){if(!userId){setTransactions([]);setLoading(false);}return;}let active=true;setLoading(true);void fetchCloudTransactions(userId).then(loaded=>{if(active){setTransactions(loaded);void syncTransactionReminders(loaded,remindersEnabled);}}).catch(error=>active&&setMessage({type:'error',text:getSupabaseErrorMessage(error,'Could not load your records.')})).finally(()=>active&&setLoading(false));return()=>{active=false};},[userId,reminderPreferenceLoaded,remindersEnabled]);
const handleAuth=async()=>{clearMessage();const cleanEmail=email.trim().toLowerCase(),cleanName=fullName.trim();if(!cleanEmail||!password){setMessage({type:'error',text:'Enter your email and password.'});return;}if(screen==='signup'&&!cleanName){setMessage({type:'error',text:'Enter your name.'});return;}if(!isSupabaseConfigured){setMessage({type:'error',text:'Supabase is not configured in this local environment.'});return;}setAuthSubmitting(true);try{const result=screen==='signin'?await signIn(cleanEmail,password):await signUp(cleanEmail,password,cleanName);if(result.error)throw result.error;if(result.data.user?.user_metadata?.full_name)setFullName(result.data.user.user_metadata.full_name);if(result.data.session){setScreen('dashboard');setMessage({type:'success',text:screen==='signin'?'Signed in successfully.':'Account created successfully.'});}else setMessage({type:'success',text:'Account created. Check your email if confirmation is enabled.'});}catch(error){setMessage({type:'error',text:getSupabaseErrorMessage(error,'Authentication failed.')});}finally{setAuthSubmitting(false);}};
const startAddTransaction=(prefillPerson='',returnScreen:Screen='dashboard')=>{setAddReturnScreen(returnScreen);setPerson(prefillPerson);setAmount('');setDueDate('');setNote('');setEntryType('lent');clearMessage();setScreen('add');};const handleSaveTransaction=async()=>{const numericAmount=Number(amount.replace(/,/g,''));if(!userId||!person.trim()||!Number.isFinite(numericAmount)||numericAmount<=0)return;setSaving(true);try{const t=await createCloudTransaction(userId,{person:person.trim(),amount:numericAmount,type:entryType,dueDate:dueDate.trim()||'No date set',note:note.trim()||'No note'});setTransactions(v=>[t,...v]);setScreen(addReturnScreen);}finally{setSaving(false);}};const handleSignOut=async()=>{if(supabase)await supabase.auth.signOut();setUserId(null);setFullName('');setTransactions([]);setScreen('welcome');};const setReminderPreference=async(v:boolean)=>{setRemindersEnabled(v);await AsyncStorage.setItem(REMINDERS_KEY,String(v));};
return {screen,setScreen,configured:isSupabaseConfigured,email,password,fullName,newPassword,userId,transactions,loading,authSubmitting,saving,message,entryType,person,amount,dueDate,note,addReturnScreen,remindersEnabled,setEmail,setPassword,setFullName,setNewPassword,setEntryType,setPerson,setAmount,setDueDate,setNote,clearMessage,handleAuth,handleSaveTransaction,handleSignOut,startAddTransaction,setReminderPreference,handleForgotPassword:async()=>{},handleUpdatePassword:async()=>{},handleToggleSettled:async()=>{},handleSendNudge:()=>{},handleDeleteTransaction:async()=>{}};}
