import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

type Props = { mode: 'signin' | 'signup'; email: string; password: string; submitting: boolean; configured: boolean; message: string | null; messageType: 'error' | 'success'; onEmailChange: (value: string) => void; onPasswordChange: (value: string) => void; onSubmit: () => void; onBack: () => void; };

export function AuthScreen({ mode, email, password, submitting, configured, message, messageType, onEmailChange, onPasswordChange, onSubmit, onBack }: Props) {
  const isSignIn = mode === 'signin';
  return <KeyboardAvoidingView style={styles.keyboard} behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={Platform.OS === 'ios' ? 8 : 0}>
    <ScrollView style={styles.scroll} contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" showsVerticalScrollIndicator={false}>
      <View style={styles.header}><Pressable onPress={onBack} hitSlop={12} style={styles.backButton}><Text style={styles.backIcon}>‹</Text><Text style={styles.backText}>Back</Text></Pressable><View style={styles.brand}><View style={styles.brandMark}><Text style={styles.brandMarkText}>O</Text></View><Text style={styles.brandText}>OweMate</Text></View><View style={styles.headerSpacer} /></View>
      <View style={styles.hero}><View style={styles.heroIcon}><Text style={styles.heroIconText}>▣</Text></View><Text style={styles.title}>{isSignIn ? 'Welcome Back!' : 'Create Account'}</Text><Text style={styles.subtitle}>Track. Remind. Settle.</Text></View>
      {message && <View style={[styles.message, messageType === 'error' ? styles.error : styles.success]}><Text style={styles.messageText}>{message}</Text></View>}
      <View style={styles.formCard}>
        <View style={styles.fieldGroup}><Text style={styles.label}>Email</Text><View style={styles.inputWrap}><Text style={styles.inputIcon}>✉</Text><TextInput value={email} onChangeText={onEmailChange} placeholder="Email" placeholderTextColor="#9AA7A5" keyboardType="email-address" autoCapitalize="none" autoCorrect={false} style={styles.input} returnKeyType="next" /></View></View>
        <View style={styles.fieldGroup}><Text style={styles.label}>Password</Text><View style={styles.inputWrap}><Text style={styles.inputIcon}>▣</Text><TextInput value={password} onChangeText={onPasswordChange} placeholder="Password" placeholderTextColor="#9AA7A5" secureTextEntry style={styles.input} returnKeyType="done" onSubmitEditing={onSubmit} /><Text style={styles.eye}>◉</Text></View></View>
        {isSignIn && <Pressable hitSlop={8} style={styles.forgot}><Text style={styles.forgotText}>Forgot Password?</Text></Pressable>}
        <Pressable style={({pressed}) => [styles.primaryButton, pressed && styles.pressed, submitting && styles.disabled]} onPress={onSubmit} disabled={submitting}>{submitting ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.primaryButtonText}>{isSignIn ? 'Sign In' : 'Create Account'}</Text>}</Pressable>
        {!configured && <Text style={styles.hint}>Supabase is not configured in this local environment yet.</Text>}
        <View style={styles.dividerRow}><View style={styles.line} /><Text style={styles.or}>or</Text><View style={styles.line} /></View>
        <Pressable style={({pressed}) => [styles.socialButton, pressed && styles.pressedLight]}><View style={styles.googleMark}><Text style={styles.googleText}>G</Text></View><Text style={styles.socialText}>Continue with Google</Text></Pressable>
        <Pressable style={({pressed}) => [styles.socialButton, pressed && styles.pressedLight]}><Text style={styles.appleMark}>●</Text><Text style={styles.socialText}>Continue with Apple</Text></Pressable>
      </View>
      <View style={styles.footer}><Text style={styles.footerText}>{isSignIn ? "Don't have an account?" : 'Already have an account?'}</Text><Pressable onPress={onBack} hitSlop={10}><Text style={styles.footerLink}>{isSignIn ? ' Sign Up' : ' Sign In'}</Text></Pressable></View>
      <Text style={styles.security}>Your records are private and securely stored.</Text>
    </ScrollView>
  </KeyboardAvoidingView>;
}

const styles = StyleSheet.create({
  keyboard:{flex:1},scroll:{flex:1,backgroundColor:'#F4F7F6'},container:{flexGrow:1,paddingHorizontal:20,paddingTop:8,paddingBottom:30},
  header:{height:50,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},backButton:{minHeight:44,flexDirection:'row',alignItems:'center',paddingRight:12},backIcon:{fontSize:28,lineHeight:30,color:'#52635F',marginRight:4},backText:{fontSize:13,fontWeight:'700',color:'#52635F'},brand:{flexDirection:'row',alignItems:'center'},brandMark:{width:30,height:30,borderRadius:10,backgroundColor:'#0F766E',alignItems:'center',justifyContent:'center',marginRight:7},brandMarkText:{color:'#FFF',fontSize:15,fontWeight:'900'},brandText:{fontSize:17,fontWeight:'900',color:'#10201D'},headerSpacer:{width:60},
  hero:{alignItems:'center',paddingTop:24,paddingBottom:22},heroIcon:{width:54,height:54,borderRadius:27,backgroundColor:'#DCEFF0',alignItems:'center',justifyContent:'center',marginBottom:12},heroIconText:{fontSize:21,color:'#0F766E',fontWeight:'900'},title:{fontSize:27,lineHeight:33,fontWeight:'900',color:'#10201D',textAlign:'center'},subtitle:{fontSize:12,color:'#7A8A87',marginTop:5},
  message:{padding:12,borderRadius:13,marginBottom:12},error:{backgroundColor:'#FFF1F2'},success:{backgroundColor:'#ECFDF5'},messageText:{fontSize:12,lineHeight:18,color:'#334155'},
  formCard:{backgroundColor:'#FFFFFF',borderRadius:22,padding:18,borderWidth:1,borderColor:'#E0E9E6',shadowColor:'#10201D',shadowOpacity:.05,shadowRadius:16,shadowOffset:{width:0,height:5},elevation:2},fieldGroup:{marginBottom:14},label:{fontSize:12,fontWeight:'800',color:'#40524E',marginBottom:7},inputWrap:{height:52,borderWidth:1,borderColor:'#D6E1DE',borderRadius:14,backgroundColor:'#FBFCFC',flexDirection:'row',alignItems:'center',paddingHorizontal:13},inputIcon:{fontSize:14,color:'#84938F',width:22,textAlign:'center'},input:{flex:1,height:50,fontSize:15,color:'#12221F',paddingVertical:0},eye:{fontSize:12,color:'#9BA6A3'},forgot:{alignSelf:'flex-end',marginTop:-4,marginBottom:13},forgotText:{fontSize:11,color:'#0F766E',fontWeight:'700'},primaryButton:{height:52,borderRadius:16,backgroundColor:'#0F766E',alignItems:'center',justifyContent:'center',marginBottom:2},pressed:{opacity:.82},disabled:{opacity:.55},primaryButtonText:{color:'#FFFFFF',fontSize:15,fontWeight:'900'},hint:{fontSize:10,lineHeight:15,color:'#8A9A96',textAlign:'center',marginTop:8},
  dividerRow:{flexDirection:'row',alignItems:'center',marginVertical:18},line:{height:1,flex:1,backgroundColor:'#E6ECEA'},or:{fontSize:10,color:'#98A4A1',marginHorizontal:10},socialButton:{height:48,borderWidth:1,borderColor:'#D7E0DE',borderRadius:15,flexDirection:'row',alignItems:'center',justifyContent:'center',marginBottom:9,backgroundColor:'#FFFFFF'},pressedLight:{backgroundColor:'#F5F9F8'},googleMark:{width:22,height:22,alignItems:'center',justifyContent:'center',marginRight:8},googleText:{fontSize:15,fontWeight:'900',color:'#4285F4'},appleMark:{fontSize:12,color:'#111827',marginRight:9},socialText:{fontSize:12,color:'#42504D',fontWeight:'700'},footer:{flexDirection:'row',justifyContent:'center',alignItems:'center',marginTop:22},footerText:{fontSize:11,color:'#7D8C88'},footerLink:{fontSize:11,color:'#0F766E',fontWeight:'900'},security:{fontSize:9,color:'#A0ACA9',textAlign:'center',marginTop:13}
});
