import { Ionicons } from '@expo/vector-icons';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useMemo } from 'react';
import { formatCurrency } from '../utils/currency';
import { parseUserDate } from '../utils/date';
import type { Transaction } from '../types/transaction';

type Props={transactions:Transaction[];userName:string;onAdd:()=>void;onPeople:()=>void;onReminders:()=>void;onNotifications:()=>void;onProfile:()=>void;onSignOut:()=>void;onToggleSettled:(transaction:Transaction)=>void;onDelete:(transaction:Transaction)=>void};
export function DashboardScreen({transactions,userName,onAdd,onPeople,onReminders,onNotifications,onProfile}:Props){const pending=transactions.filter(x=>x.status!=='settled');const lent=pending.filter(x=>x.type==='lent').reduce((s,x)=>s+x.amount,0);const borrowed=pending.filter(x=>x.type==='owed').reduce((s,x)=>s+x.amount,0);const upcoming=useMemo(()=>[...pending].sort((a,b)=>(parseUserDate(a.dueDate)?.getTime()??Infinity)-(parseUserDate(b.dueDate)?.getTime()??Infinity)).slice(0,3),[transactions]);return <View style={s.screen}><ScrollView contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.title}>Hi, {userName || 'there'}</Text><Text style={s.subtitle}>Here’s your money overview</Text></View><View style={s.headerActions}><Pressable onPress={onNotifications} style={s.iconButton}><Ionicons name="notifications-outline" size={24}/></Pressable><Pressable onPress={onProfile} style={s.iconButton}><Ionicons name="person-circle-outline" size={28}/></Pressable></View></View><View style={s.card}><Text>Outstanding Balance</Text><Text style={s.amount}>{formatCurrency(lent-borrowed)}</Text></View><View style={s.row}><View style={[s.card,s.half]}><Text>You Lent</Text><Text style={s.lent}>{formatCurrency(lent)}</Text></View><View style={[s.card,s.half]}><Text>You Borrowed</Text><Text style={s.borrowed}>{formatCurrency(borrowed)}</Text></View></View><Pressable style={s.add} onPress={onAdd}><Text style={s.addText}>+ Add Transaction</Text></Pressable><Text style={s.section}>Upcoming Dues</Text>{upcoming.map(x=><Pressable key={x.id} style={s.item} onPress={onPeople}><View><Text style={s.person}>{x.person}</Text><Text>{x.dueDate}</Text></View><Text style={x.type==='owed'?s.borrowed:s.lent}>{formatCurrency(x.amount)}</Text></Pressable>)}</ScrollView><View style={s.nav}><Pressable style={s.navItem}><Text>Home</Text></Pressable><Pressable style={s.navItem} onPress={onPeople}><Text>Transactions</Text></Pressable><Pressable style={s.navItem} onPress={onAdd}><Text>Add</Text></Pressable><Pressable style={s.navItem} onPress={onReminders}><Text>Calendar</Text></Pressable><Pressable style={s.navItem} onPress={onProfile}><Text>Profile</Text></Pressable></View></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#F8F9FF'},content:{padding:20,paddingBottom:100},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},headerActions:{flexDirection:'row',gap:6},iconButton:{padding:6},title:{fontSize:24,fontWeight:'800',color:'#00685F'},subtitle:{fontSize:13,color:'#667371',marginTop:3},card:{backgroundColor:'#fff',padding:16,borderRadius:14,marginBottom:12},half:{flex:1},amount:{fontSize:32,fontWeight:'800',marginTop:4},row:{flexDirection:'row',gap:12},lent:{color:'#006947',fontSize:18,fontWeight:'700'},borrowed:{color:'#B90538',fontSize:18,fontWeight:'700'},add:{backgroundColor:'#00685F',padding:16,borderRadius:28,alignItems:'center',marginVertical:12},addText:{color:'#fff',fontWeight:'800',fontSize:16},section:{fontSize:20,fontWeight:'800',marginVertical:12},item:{backgroundColor:'#fff',padding:14,borderRadius:12,marginBottom:8,flexDirection:'row',justifyContent:'space-between'},person:{fontSize:16,fontWeight:'700'},nav:{position:'absolute',bottom:0,left:0,right:0,height:72,backgroundColor:'#fff',flexDirection:'row',borderTopWidth:1,borderColor:'#eee'},navItem:{flex:1,alignItems:'center',justifyContent:'center'}});